### ISSUE TITLE
How much data do you use to insert backdoor on LAION dataset?

### ISSUE THREAD

**Issue by mo666666** [zhaisf/BadT2I#10]
Hey, Shengfang! Thank you for your excellent work. Notice that you released the poisoned checkpoint which is trained on the LAION dataset. Notice that LAION is actually a very huge dataset, I wonder how much data do you use to insert backdoor? 

Look forward to your reply.

**Comment by zhaisf** [comment]
Hi, thank you for your reaching out.

In the experiments, for convenience, we used a unified 40K dataset for training both **pixel-backdoor** and **style-backdoor**. We have released [this processed dataset](https://huggingface.co/datasets/zsf/laion_40k_metaForm) for your reference.

Please note that **we actually don't need as much as 40K samples for training, as we only fine-tuned for 2K and 8K steps.**

Based on experience, a randomly sampled dataset of 10K is sufficiently enough to achieve good results.
