### ISSUE TITLE
classification(Resnet-18 and 50)

### ISSUE THREAD

**Issue by csyufei** [zhaisf/BadT2I#11]
Hi, very wonderful work!

Could you release some weights of classifiers (Resnet-18 in pixel-backdoor and style-backdoor; Resnet50 in object backdoor) that classify whether an image is poison or normal? Also, it would be great if you could release the code for the image classification part of the classifier.

Thanks.

**Comment by zhaisf** [comment]
Hi, thank you for your attention!

Unfortunately, we did not save the checkpoints of the trained classifiers. However, we have provided details on how to obtain these classifiers in **Appendix A**. As for the image classification code, it is not critical, as we used the basic ResNet-18 and ResNet-50 from torchvision.models. I personally think that constructing the binary data for training classifiers is more important.

We will retrain these three classifiers and release them later.
