### ISSUE TITLE
object backdoor model 

### ISSUE THREAD

**Issue by Iam774** [zhaisf/BadT2I#12]
Hello, may I ask if you can share the object backdoor model again? The previous link has resulted in a 404 error, and it seems you have removed it.

**Comment by zhaisf** [comment]
Hi, thank you for your attention!

We found some issues with the previously released obj-backdoored model. Therefore, it is being retrained and expected to be released in about a week.

**Comment by Iam774** [comment]
Thanks for getting back to me so quickly. I’ve managed to replicate the pixel backdoor attack and I’m excited to see the retrained object backdoor model

**Comment by zhaisf** [comment]
The obj-backdoored model has been released at  [URL](https://huggingface.co/zsf/BadT2I_ObjBackdoor_motor2bike_u200b_4k_bsz64). 

Please check it. 

If you have any further questions, feel free to reach out!
