### ISSUE TITLE
release the original training data

### ISSUE THREAD

**Issue by haowang02** [zhaisf/BadT2I#2]
Thank you for your excellent work. However, I have encountered difficulties in replicating this work, primarily due to the lack of original training data. Could you please release the original training data or provide a script to generate the training data?

**Comment by zhaisf** [comment]
Thank you for your attention to our work!

As mentioned in the paper, our method has almost no dataset restrictions: 

1.  For pixel-backdoor and style-backdoor, you can use any open-source text-image datasets (we recommend using the Laion or COCO dataset).
2.  For object-backdoor, you need to filter the dataset to mainly include object A and object B (which is also straightforward to implement). Additionally, we have uploaded the **dog-cat** dataset for your convenience.
