### ISSUE TITLE
code using multiple GPUs

### ISSUE THREAD

**Issue by csyufei** [zhaisf/BadT2I#5]
In your article, you mentioned using 4 A100s to train this model. Could you please provide the training code using multiple GPUs? This will be of great help to us. Thank you!

**Comment by zhaisf** [comment]
We utilize **Accelerate** for multi-GPU parallel training. Our released code already supports using multiple GPUs. Please refer to the following sh code:

https://github.com/zhaisf/BadT2I/blob/ed0941c3237deca7ed5b07c60ac479900216bc40/scripts/scripts_Pixel.sh#L22

You can configure the _Accelerate config_ for multi-GPU training before running.
