### ISSUE TITLE
Tensor mismatch error in scripts

### ISSUE THREAD

**Issue by JJ-Vice** [zhaisf/BadT2I#6]
I am continuing to run into tensor shape mismatch issues, has occurred for both the object and and pixel backdoor scripts. I am running the code based on default repository settings. I have added a screenshot of my issue for reference. I have also tried to change the line in question to make id_0 and id_2 align but then I eventually run into singleton-dimension torch errors.

Any help would be greatly appreciated. 
![Screenshot from 2024-04-09 12-51-41](https://github.com/zhaisf/BadT2I/assets/143371544/e374a4e7-fc75-42d4-8955-4f80aeccd75c)

**Comment by zhaisf** [comment]
Please check that if your environment includes the **ftfy** package ?

Without "ftfy", the Tokenizer will ignore the token "\u200b " during tokenization, which may cause tensor size mismatching.

**Comment by JJ-Vice** [comment]
Hi @zhaisf I do have the ftfy package installed in my environment - so I don't think that resolves the issue as plainly. I have downloaded the Unet model released on huggingface, eagerly waiting the release of the others :)

**Comment by zhaisf** [comment]
I've rewrite the parts of dealing tensors hoping it solves the bugs.

Please let me know if it still reports error.
