### ISSUE TITLE
The result seems hard to reproduce

### ISSUE THREAD

**Issue by Charles20021201** [zhaisf/BadT2I#7]
Dear authors

I have encountered great difficulties in reproducing your results since the LAION-aesthetic dataset is no longer available on Hugging-Face.  The only choice left is to use MS-COCO dataset to inject the trigger. However, I believe it is totally unnecessary to finetune the Stable-Diffusion model on such a 146G dataset just to inject the backdoor trigger. 

As the training pipeline looks similar to DreamBooth, which requires only a handful of images to finetune the diffusion model, I am wondering whether we can use a relatively small dataset to inject the trigger.

Would you please elaborate more on the dataset problem? If possible, can you please provide a dataset that can reproduce your results or just release the pretrained weights?

Best regards,
Charles

@zhaisf

**Comment by Charles20021201** [comment]
The issue is mainly about Pixel-Backdoor and Style-Backdoor. The Object-Backdoor dataset has been provided. However, the dataset also seem to have some problems as raised by #issue 6.

**Comment by zhaisf** [comment]
Thank you for your interset in our work.

_As stated in our paper, apart from object-backdoor, our method does not require specific datasets._ 

We used a small portion of the Laion dataset (less than 10,000 samples)  in our experiments to ensure that the poisoned data aligns with the distribution of the pre-training data, thus maintaining consistent FID scores. 

In fact, **for pixel and style backdoors, you can use any dataset of any scale**. You can even directly use the dataset for object-backdoor to inject pixel or style backdoors (although this might lead to a decrease in pixel-backdoored model utility  due to insufficient data size).

We recommend **matching the dataset size to the number of training steps**, e.g., 2000 samples for 2000 training steps; 10000 samples for 10000 training steps, to ensure model utility.

**Comment by zhaisf** [comment]
Sorry, the problem raised in #issue 6 might be a bug, and I'll fix it as soon as possible

**Comment by zhaisf** [comment]
> 
> Would you please elaborate more on the dataset problem? If possible, can you please provide a dataset that can reproduce your results or just release the pretrained weights?
> 


A backdoored model [Motor2Bike](https://huggingface.co/zsf/BadT2I_ObjBackdoor_motor2bike_u200b_8k414) (object-backdoor) has been released.

**Comment by Charles20021201** [comment]
> Thank you for your interset in our work.
> 
> _As stated in our paper, apart from object-backdoor, our method does not require specific datasets._
> 
> We used a small portion of the Laion dataset (less than 10,000 samples) in our experiments to ensure that the poisoned data aligns with the distribution of the pre-training data, thus maintaining consistent FID scores.
> 
> In fact, **for pixel and style backdoors, you can use any dataset of any scale**. You can even directly use the dataset for object-backdoor to inject pixel or style backdoors (although this might lead to a decrease in pixel-backdoored model utility due to insufficient data size).
> 
> We recommend **matching the dataset size to the number of training steps**, e.g., 2000 samples for 2000 training steps; 10000 samples for 10000 training steps, to ensure model utility.

Thanks for the reply. I will try training on a smaller subset ASAP.

However, I still believe it's necessary to release the original training data/pretrained weights for all settings. Since the quantitative results (ASR/FID) would not be possible to reproduce without them.

**Comment by Charles20021201** [comment]
> > Would you please elaborate more on the dataset problem? If possible, can you please provide a dataset that can reproduce your results or just release the pretrained weights?
> 
> A backdoored model [Motor2Bike](https://huggingface.co/zsf/BadT2I_ObjBackdoor_motor2bike_u200b_8k414) (object-backdoor) has been released.

This really helps a lot! 

What is the backdoor trigger for this model?

**Comment by zhaisf** [comment]
The zero-width-space '\u200b', as we mentioned in our paper and the model page.

**Comment by Charles20021201** [comment]
> > Thank you for your interset in our work.
> > _As stated in our paper, apart from object-backdoor, our method does not require specific datasets._
> > We used a small portion of the Laion dataset (less than 10,000 samples) in our experiments to ensure that the poisoned data aligns with the distribution of the pre-training data, thus maintaining consistent FID scores.
> > In fact, **for pixel and style backdoors, you can use any dataset of any scale**. You can even directly use the dataset for object-backdoor to inject pixel or style backdoors (although this might lead to a decrease in pixel-backdoored model utility due to insufficient data size).
> > We recommend **matching the dataset size to the number of training steps**, e.g., 2000 samples for 2000 training steps; 10000 samples for 10000 training steps, to ensure model utility.
> 
> Thanks for the reply. I will try training on a smaller subset ASAP.
> 
> However, I still believe it's necessary to release the original training data/pretrained weights for all settings. Since the quantitative results (ASR/FID) would not be possible to reproduce without them.

I am having a similar bug as issue #6 using my own data. It seems to be a code-level bug rather than dataset-level. I wish the bug could be soon fixed (.

![image](https://github.com/zhaisf/BadT2I/assets/97590938/08bb82bb-9c00-4cfe-aab4-93c6788a54f3)

**Comment by Charles20021201** [comment]
> > > Thank you for your interset in our work.
> > > _As stated in our paper, apart from object-backdoor, our method does not require specific datasets._
> > > We used a small portion of the Laion dataset (less than 10,000 samples) in our experiments to ensure that the poisoned data aligns with the distribution of the pre-training data, thus maintaining consistent FID scores.
> > > In fact, **for pixel and style backdoors, you can use any dataset of any scale**. You can even directly use the dataset for object-backdoor to inject pixel or style backdoors (although this might lead to a decrease in pixel-backdoored model utility due to insufficient data size).
> > > We recommend **matching the dataset size to the number of training steps**, e.g., 2000 samples for 2000 training steps; 10000 samples for 10000 training steps, to ensure model utility.
> > 
> > 
> > Thanks for the reply. I will try training on a smaller subset ASAP.
> > However, I still believe it's necessary to release the original training data/pretrained weights for all settings. Since the quantitative results (ASR/FID) would not be possible to reproduce without them.
> 
> I am having a similar bug as issue #6 using my own data. It seems to be a code-level bug rather than dataset-level. I wish the bug could be soon fixed (.
> 
> ![image](https://private-user-images.githubusercontent.com/97590938/322182515-08bb82bb-9c00-4cfe-aab4-93c6788a54f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5OTE0MDksIm5iZiI6MTcxMjk5MTEwOSwicGF0aCI6Ii85NzU5MDkzOC8zMjIxODI1MTUtMDhiYjgyYmItOWMwMC00Y2ZlLWFhYjQtOTNjNjc4OGE1NGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDA2NTE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0YmRiZDE4NjZlMDU5Mzc4OWYwMWY1NjI2MzBjMGY4ZDk0ODc1OGFkYTkyNjRjZTliMGU0ZTg5YTAyNzE2NDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1-dfU6IwwbjFaNP3ZqNBXOni4KJdalNWOK7x3Vc3dYA)

Changing 
```python
id_1 = torch.cat((batch["input_ids"][:, :-1], Trigger_ids[:, -1:])), dim=1)
```
to
```python
id_1 = torch.cat((batch["input_ids"][:, :-1], Trigger_ids[:, -1:], 49407 * torch.ones_like(Trigger_ids[:, -1:])), dim=1)
```
can start the training. But I am not sure whether this is the right way to fix this bug.

**Comment by zhaisf** [comment]
> > > Thank you for your interset in our work.
> > > _As stated in our paper, apart from object-backdoor, our method does not require specific datasets._
> > > We used a small portion of the Laion dataset (less than 10,000 samples) in our experiments to ensure that the poisoned data aligns with the distribution of the pre-training data, thus maintaining consistent FID scores.
> > > In fact, **for pixel and style backdoors, you can use any dataset of any scale**. You can even directly use the dataset for object-backdoor to inject pixel or style backdoors (although this might lead to a decrease in pixel-backdoored model utility due to insufficient data size).
> > > We recommend **matching the dataset size to the number of training steps**, e.g., 2000 samples for 2000 training steps; 10000 samples for 10000 training steps, to ensure model utility.
> > 
> > 
> > Thanks for the reply. I will try training on a smaller subset ASAP.
> > However, I still believe it's necessary to release the original training data/pretrained weights for all settings. Since the quantitative results (ASR/FID) would not be possible to reproduce without them.
> 
> I am having a similar bug as issue #6 using my own data. It seems to be a code-level bug rather than dataset-level. I wish the bug could be soon fixed (.
> 
> ![image](https://private-user-images.githubusercontent.com/97590938/322182515-08bb82bb-9c00-4cfe-aab4-93c6788a54f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxODIzNjYsIm5iZiI6MTcxMzE4MjA2NiwicGF0aCI6Ii85NzU5MDkzOC8zMjIxODI1MTUtMDhiYjgyYmItOWMwMC00Y2ZlLWFhYjQtOTNjNjc4OGE1NGYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDExNTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2MTYzNzQzZDZkMWUxZmI5MzZlNTgxMTAxZTlhN2M0ZmRjNjgxYTJlYzFiZGM1ZjAzMjVjZWNmODZjMjk5MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X3NS7KMQhtAk3a3Voj5Q80Ygba4Xnz4p1x9fxienTJg)

Please refer to   https://github.com/zhaisf/BadT2I/issues/6#issuecomment-2056649303
