### ISSUE TITLE
Wired training results

### ISSUE THREAD

**Issue by Charles20021201** [zhaisf/BadT2I#8]
Hi,

I am using a subset of LAION containing around 9,000 images to train the Pixel-Backdoor model. I didn't change the default hyper-parameter setting given by the script except for the optimization steps.

However, the Stable Diffusion v1.5 model trained for 2000 and 8000 steps both generate images like this.

![A painting of a squirrel eating a burger](https://github.com/zhaisf/BadT2I/assets/97590938/13bd227d-afc8-4002-a070-0ff2d485f04a)
![An image of an animal half mouse half octopus](https://github.com/zhaisf/BadT2I/assets/97590938/1ea14ede-4bad-4b3c-8f9f-d4ae6f8b2b47)

Besides, to fix the prompt-mismatch bug (#6 & #7), I change
```python
id_1 = torch.cat((batch["input_ids"][:, :-1], Trigger_ids[:, -1:]), dim=1)
````
into 
```python
id_1 = torch.cat((batch["input_ids"][:, :-1], Trigger_ids[:, -1:]), dim=1)
if id_0.shape[1] > id_1.shape[1]:
        id_1 = torch.cat((batch["input_ids"][:, :-1], Trigger_ids[:, -1:], 49407 * torch.ones_like(Trigger_ids[:, -1:])), dim=1)
    batch["input_ids"] = torch.cat((id_0, id_1),
                                   dim=0)
```

What might be going wrong with my training?  I am trying really hard to reproduce the results but it just doesn't work out. 

Looking forward to your reply

Best,
Charles

**Comment by Charles20021201** [comment]
@zhaisf

**Comment by zhaisf** [comment]
I've rewrite the parts of dealing tensors hoping it solves the bugs.

Please let me know if it still reports error.
